
version: '3.8'

services:
  api_service:
    build: .
    ports:
      - "8088:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/sdpproject?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - springapimysql-net

  mysqldb:
    image: mysql:8.0  # Specify a version instead of latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: sdpproject
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - springapimysql-net

networks:
  springapimysql-net:
